name: Composite action

runs:
  using: "composite"
  steps:
    - name: primer step composite
      id: step1composite
      shell: bash
      run: |
        echo $variablecomposite
        pwd
        ls -l
        env
        ls -lrt ${{ github.action_path }}
        echo "github_env_variable=prueba" >> "$GITHUB_ENV"
    - name: segundo step composite
      id: step2composite
      shell: bash
      run: |
        env
        echo $variablecomposite
        bash ${{ github.action_path }}/script.sh
